### ISSUE TITLE
`getBM()` error: `Mart` object has no `http_config` slot name

### ISSUE THREAD

**Issue by listvennica** [grimbough/biomaRt#114]
Dear colleagues,

I've stuck with a problem: R cannot find `http_config` slot name for `Mart` object. I guess that may be related to the recent API change (`httr_config` was changed to `http_config`), but I've no idea why the method uses different slot name.

I've tried to upgrade biomaRt, downgrade biomaRt, upgrade all packages, and nothing worked, the problem persists.

Could you give me a clue what's wrong?

MWE:

``` r
library (biomaRt)
library (ChIPseeker)
library (ChIPpeakAnno)
library (GenomicRanges)
library (TxDb.Dmelanogaster.UCSC.dm6.ensGene)

ensembl <- readRDS ('ensembl.RDS')
attr_chos <- c ('ensembl_gene_id', 'entrezgene_id', 'flybase_annot_id', 'external_gene_name')
heatmap_anno <- annotatePeak (GRanges (c ('chr3R:17624985-17625485')), tssRegion = c (-200, 200), TxDb = TxDb.Dmelanogaster.UCSC.dm6.ensGene)
getBM ( mart = ensembl, filters = 'ensembl_gene_id', values = heatmap_anno, attributes = attr_chos )
#> Error in do.call(c, obj@http_config): нет слота имени "http_config" для этого объекта класса "Mart"
```

---

Versions:

```bash
lsb_release -a
# Description:    Debian GNU/Linux 12 (bookworm)

R --version
# R version 4.4.2 (2024-10-31) -- "Pile of Leaves"
# Platform: x86_64-pc-linux-gnu
```

``` r
BiocManager::version ()
#> [1] ‘3.19’

packageVersion ('biomaRt')
#> [1] ‘2.60.1’
```

**Comment by grimbough** [comment]
When did you save the `ensembl` object stored in `'ensmbl.RDS'`?  Could that be from an older version of biomaRt.  What happens if you create a new version using `use_ensembl()`?

**Comment by lattaai7** [comment]
Hello, I tried to solve the issue.

This is what I did:

Updated the Mart class definition to include the http_config slot, and modified related methods to use http_config instead of httr_config.

You can review changes in this commit: https://github.com/lattaai7/grimbough-biomaRt-114/commit/705952f211c1dd18039a52b4a6f9c4e427eb7191.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by listvennica** [comment]
> When did you save the `ensembl` object stored in `'ensmbl.RDS'`? Could that be from an older version of biomaRt. What happens if you create a new version using `use_ensembl()`?

I've missed the elephant in the room. `ensembl.RDS` was really created ages ago. Thank you, it helped!
