### ISSUE TITLE
Problem with useMart specifying the host mar2016

### ISSUE THREAD

**Issue by JFerrer-B** [grimbough/biomaRt#48]
I'm working with the host mar2016.archive.ensembl.org

It seems it is not available anymore. Is this the case or it will be available again?

**Comment by grimbough** [comment]
I'm afraid the majority of Ensembl archives are only maintained for 5 years, so the March 2016 archive has now been retired.

There's some more details on archive life span available [here](http://mart.ensembl.org/info/website/archives/index.html)
