### ISSUE TITLE
Missing link of numbers of Orthologs between mouse and human

### ISSUE THREAD

**Issue by tt342400** [grimbough/biomaRt#62]
Hi,

By using getLDS converting mouse genes to human orthologs, I found that lots of Orthologs were missing.

They were Rps27a, Rpl13a, Rps17.....

It seems that bioMart specifically lost the link between mouse and human for ribosomal proteins.

**Comment by grimbough** [comment]
The biomaRt package is just an interface to the data in Ensembl. I'm afraid I don't have any control or insight into the actual data content.  

If you think theres an issue with the data, or you'd like to know the reasoning behind a change, I think you're best off contacting the Ensembl help desk directly at https://www.ensembl.org/info/about/contact/index.html
