### ISSUE TITLE
getLDS Error

### ISSUE THREAD

**Issue by ESUIT-SU** [grimbough/biomaRt#63]
Hi，when I use getLDS：
geneMm <- getLDS(attributes = "hgnc_symbol",filters="hgnc_symbol",values=genelist,mart=human,attributesL = "mgi_symbol",martL=mouse,uniqueRows = TRUE)

Error: biomaRt has encountered an unexpected server error.
Consider trying one of the Ensembl mirrors (for more details look at ?useEnsembl)

What is the problem？

**Comment by grimbough** [comment]
Thanks for the report. I'm tracking this error in #61
