### ISSUE TITLE
Error in curl

### ISSUE THREAD

**Issue by Rom1M** [grimbough/biomaRt#67]
Hi, 
Could someone help me with the following issue:
When i run the code below, I get the error message : 

_Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to api.cryptowat.ch port 443: Timed out_

Code:
_install.packages('cryptowatchR')
library ('cryptowatchR')
my_url <- paste("https://api.cryptowat.ch/assets")
result <- httr::GET(my_url)_

The weird thing is that I ran exactly the same code on Rstudio on my private laptop and I didn't face this issue. A colleague of mine who is using the same environment has no issue either.

Looking forward to your tips on this one, 

Many thanks in advance

**Comment by grimbough** [comment]
Hi @Rom1M 

I'm not sure you've posted this in the right place.  This repository is the R package biomaRt and has nothing to do with cryptowat.ch or general HTTP queries.  You might get a better response asking at https://github.com/r-lib/httr
