### ISSUE TITLE
DESCRIPTION: URL and BugReports

### ISSUE THREAD

**Issue by HenrikBengtsson** [grimbough/biomaRt#75]
Please consider adding `URL` and `BugReports` pointing to this GitHub repo and issue tracker to your DESCRIPTION file.  That way, it'll be easier to find this repo, e.g. from https://www.bioconductor.org/packages/biomaRt.

**Comment by grimbough** [comment]
This should now be done.  I didn't realise that biomaRt was lacking those fields, most of my other packages have them.  Thanks for pointing it out.
