### ISSUE TITLE
Possible SSL connectivity problems detected.

### ISSUE THREAD

**Issue by rubie7109** [grimbough/biomaRt#81]
> listEnsembl()
Possible SSL connectivity problems detected.
Please report this issue at https://github.com/grimbough/biomaRt/issues
Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL peer certificate or SSH remote key was not OK: [uswest.ensembl.org] SSL certificate problem: certificate has expired

I see this issue has been noted and a resolution was attempted 2 days ago, however it appears the us-west mirror is still in reference. FYI I downloaded the biomaRt package today.

Thanks!

**Comment by simfor** [comment]
I still get the exact same error. So it seems like the query is still sent to the us-west mirror. I use biomart version 2.54.1

**Comment by grimbough** [comment]
The fix to this issue was made in biomaRt version 2.57.1 or newer, which is available in Bioconductor 3.17.

Unfortunately it's not possible to backport it to older versions of the package.
