### ISSUE TITLE
dump error

### ISSUE THREAD

**Issue by abrionne** [grimbough/biomaRt#90]
It's seems that bioMart have some difficulites to connect to Ensembl.
Several people ask me why my package (ViSEAGO) no works with Ensembl  from several days.

It's seems provide from collect() according the printed error.

> library(biomaRt)
> listEnsembl()
Error in `collect()`:
! Failed to collect lazy table.
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?
Run `rlang::last_trace()` to see where the error occurred.

> sessionInfo()
R version 4.3.2 (2023-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 21.2

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8     LC_MONETARY=fr_FR.UTF-8   
 [6] LC_MESSAGES=fr_FR.UTF-8    LC_PAPER=fr_FR.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Paris
tzcode source: system (glibc)

**Comment by grimbough** [comment]
This looks like the error reported in https://github.com/grimbough/biomaRt/issues/89 which is fixed by updating to the latest version of BiocFileCache.

**Comment by abrionne** [comment]
oh thank you!

sorry for the inconvenience

Aurélien
