### ISSUE TITLE
Unable to use biomaRt

### ISSUE THREAD

**Issue by NTherrien93** [grimbough/biomaRt#94]
When trying to view databases with `biomaRt::listEnsembl()` I receive the following error:

Error in `collect()`:
! Failed to collect lazy table.
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?
Backtrace:
  1. `biomaRt::useEnsembl(biomart = "genes", dataset = "hsapiens_gene_ensembl")`
 11. `dbplyr:::collect.tbl_sql(., Inf)`
 16. `dbplyr::db_collect(x$src$con, sql, n = n, warn_incomplete = warn_incomplete, ...)`
Error in collect(., Inf) :
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?

Do you have recommendations on how to resolve this issue?

**Comment by grimbough** [comment]
This is caused by having an out-of-date version of `BiocFileCache`.  There's some more details and suggested solutions in this support site post: https://support.bioconductor.org/p/9154901/#9154924
